#!/usr/bin/env perl
use strict;
use warnings;
use JSON::PP qw(encode_json decode_json);
use File::Path qw(make_path);
use Digest::SHA qw(sha256_hex);
use POSIX qw(strftime);

my $GATEWAY_DIR    = '/local_opt/lab-vllm-gateway';
my $STUDENTS_FILE  = "$GATEWAY_DIR/config/students_tokens.json";
my $CONFIG_FILE    = "$GATEWAY_DIR/config/gateway_config.json";
my $NGINX_CONF     = '/etc/nginx/conf.d/vllm-gateway.conf';
my $NGINX_MAIN     = '/etc/nginx/nginx.conf';
my $NGINX_LOG      = '/var/log/nginx/vllm-gateway-access.log';
my $NGINX_ERR_LOG  = '/var/log/nginx/vllm-gateway-error.log';
my $PID_FILE       = '/var/run/nginx.pid';

my $action = shift @ARGV || 'status';

sub main {
    my $actions = {
        setup             => \&setup,
        install           => \&setup,
        start             => sub { generate_nginx_config(); nginx_sys('start') },
        stop              => sub { nginx_sys('stop') },
        restart           => sub { generate_nginx_config(); nginx_sys('restart') },
        reload            => sub { generate_nginx_config(); nginx_sys('reload') },
        status            => \&show_status,
        generate          => \&generate_nginx_config,
        'add-student'     => \&add_student,
        'remove-student'  => \&remove_student,
        'set-student-limits' => \&set_student_limits,
        'list-students'   => \&list_students,
        help              => \&usage,
    };

    if (my $code = $actions->{$action}) {
        $code->();
    } else {
        die "Unknown action: $action\n";
    }
}

sub setup {
    print "=== Installing nginx... ===\n";
    my $inst = system("rpm -q nginx >/dev/null 2>&1");
    if ($inst != 0) {
        my $out = `yum install -y nginx 2>&1`;
        print $out;
        die "nginx install failed" if $?;
    } else {
        print "nginx already installed\n";
    }

    make_path('/etc/nginx/conf.d');
    make_path('/local_opt/lab-vllm-gateway/run');
    make_path('/local_opt/lab-vllm-gateway/logs');
    make_path('/local_opt/lab-vllm-gateway/config');

    generate_nginx_config();
    nginx_sys('enable');
    nginx_sys('start');

    print "Gateway setup OK. Port 9000 -> node13:8000\n";
}

sub generate_nginx_config {
    my $cfg = read_config();
    my $students = read_students();

    my $backend_host = $cfg->{backend_host} || 'node13';
    my $backend_port = $cfg->{backend_port} || 8000;
    my $gw_port      = $cfg->{gateway_port} || 9000;
    my $public_model = $cfg->{public_model_name} || 'qwen3.6-35b-a3b-fp8';
    my $rpm_limit    = $cfg->{rpm_limit} || 60;
    my $client_to    = $cfg->{client_timeout} || 60;
    my $down_to      = $cfg->{downstream_timeout} || 600;
    my $hard_to      = $cfg->{request_hard_timeout} || 900;

    my $backend = "http://$backend_host:$backend_port";

    my $map_entries = '';
    for my $sid (sort keys %$students) {
        my $s = $students->{$sid};
        next unless $s->{enabled};
        my $token = $s->{token};
        next unless $token;
        $map_entries .= "    \"Bearer $token\" \"$sid\";\n";
    }

    my $conf = <<"NGINX_CONF";
# Auto-generated by deploy_nginx_gateway_v022_qwen35b.pl
# Generated: @{[strftime('%Y-%m-%d %H:%M:%S', localtime)]}

limit_req_zone \$http_authorization zone=gw_rl:10m rate=${rpm_limit}r/m;

map \$http_authorization \$gw_student_id {
    default     "";
$map_entries
}

server {
    listen $gw_port;
    server_name _;

    access_log $NGINX_LOG;
    error_log  $NGINX_ERR_LOG;

    client_max_body_size 100m;
    proxy_connect_timeout ${client_to}s;
    proxy_read_timeout    ${hard_to}s;
    proxy_send_timeout    ${hard_to}s;

    location = /healthz {
        access_log off;
        default_type application/json;
        return 200 '{"status":"ok","public_model":"$public_model","backend_host":"$backend_host","backend_port":$backend_port,"gateway_port":$gw_port}';
    }

    location /v1/ {
        if (\$gw_student_id = "") {
            add_header WWW-Authenticate 'Bearer realm="vllm-gateway"' always;
            return 401 '{"error":"missing or invalid token"}';
        }

        limit_req zone=gw_rl burst=20 nodelay;
        limit_req_status 429;

        proxy_pass $backend;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Host $backend_host:$backend_port;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Student-ID \$gw_student_id;

        proxy_set_header X-Accel-Buffering no;
        proxy_buffering off;

        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
    }
}
NGINX_CONF

    open my $fh, '>', $NGINX_CONF or die "Cannot write $NGINX_CONF: $!\n";
    print $fh $conf;
    close $fh;
    print "Generated: $NGINX_CONF\n";
}

sub nginx_sys {
    my ($cmd) = @_;
    if ($cmd eq 'enable') {
        system('systemctl enable nginx 2>&1');
    } elsif ($cmd eq 'start') {
        system('systemctl start nginx 2>&1');
        print "nginx started\n";
    } elsif ($cmd eq 'stop') {
        system('systemctl stop nginx 2>&1');
        print "nginx stopped\n";
    } elsif ($cmd eq 'restart') {
        system('systemctl restart nginx 2>&1');
        print "nginx restarted\n";
    } elsif ($cmd eq 'reload') {
        system('nginx -t 2>&1') and die "nginx config test failed";
        system('systemctl reload nginx 2>&1');
        print "nginx reloaded\n";
    }
}

sub show_status {
    my $cfg = read_config();
    my $backend_host = $cfg->{backend_host} || 'node13';
    my $backend_port = $cfg->{backend_port} || 8000;
    my $gw_port = $cfg->{gateway_port} || 9000;

    print "=== nginx status ===\n";
    my $nginx_running = `systemctl is-active nginx 2>/dev/null`; chomp $nginx_running;
    print "nginx: $nginx_running\n";
    if ($nginx_running eq 'active') {
        print "Config: $NGINX_CONF\n";
        print "Listen: port $gw_port\n";
    }

    print "\n=== Backend health ===\n";
    my $health = `curl -s -o /dev/null -w '%{http_code}' http://$backend_host:$backend_port/health 2>/dev/null`;
    print "node13:$backend_port: HTTP $health\n";

    print "\n=== Gateway health ===\n";
    my $gw_health = `curl -s http://127.0.0.1:$gw_port/healthz 2>/dev/null`;
    print "$gw_health\n";

    print "\n=== Students ===\n";
    list_students();
}

sub read_config {
    if (-f $CONFIG_FILE) {
        open my $fh, '<', $CONFIG_FILE or die "Cannot read $CONFIG_FILE: $!\n";
        local $/;
        return decode_json(<$fh>);
    }
    return {
        backend_host => 'node13',
        backend_port => 8000,
        gateway_port => 9000,
        public_model_name => 'qwen3.6-35b-a3b-fp8',
        rpm_limit => 60,
        client_timeout => 60,
        downstream_timeout => 600,
        request_hard_timeout => 900,
    };
}

sub read_students {
    return {} unless -f $STUDENTS_FILE;
    open my $fh, '<', $STUDENTS_FILE or die "Cannot read $STUDENTS_FILE: $!\n";
    local $/;
    my $raw = decode_json(<$fh>);
    return $raw->{students} || {};
}

sub write_students {
    my ($data) = @_;
    make_path("$GATEWAY_DIR/config");
    open my $fh, '>', $STUDENTS_FILE or die "Cannot write $STUDENTS_FILE: $!\n";
    print $fh encode_json({students => $data}) . "\n";
    close $fh;
}

sub gen_token {
    my $raw = shift @_ // time . rand(99999);
    return sha256_hex($raw);
}

sub add_student {
    my $sid = shift @ARGV || '';
    if ($sid =~ /^--student-id=(.+)$/) { $sid = $1 }

    my %opts;
    for (@ARGV) {
        if (/^--student-id=(.+)$/)     { $sid = $1 }
        elsif (/^--token=(.+)$/)       { $opts{token} = $1 }
        elsif (/^--allow-ip=(.+)$/)    { $opts{allow_ip} = $1 }
        elsif (/^--max-concurrent=(.+)$/){ $opts{max_concurrent} = $1 }
        elsif (/^--rpm-limit=(.+)$/)   { $opts{rpm_limit} = $1 }
    }

    die "Usage: add-student --student-id=ID [--token=TOKEN] [--allow-ip=IP]\n" unless $sid;

    my $students = read_students();
    die "Student '$sid' already exists\n" if exists $students->{$sid};

    $opts{token} ||= gen_token($sid . time . rand(99999));
    $opts{enabled} = JSON::PP::true;
    $opts{created_at} = strftime('%Y-%m-%d %H:%M:%S', localtime);
    $opts{updated_at} = $opts{created_at};

    $students->{$sid} = \%opts;
    write_students($students);

    generate_nginx_config();
    nginx_sys('reload');

    print "Added student: $sid\n";
    print "  Token: $opts{token}\n";
    print "  Model: " . (read_config()->{public_model_name} || 'qwen3.6-35b-a3b-fp8') . "\n";
}

sub remove_student {
    my $sid = shift @ARGV || '';
    if ($sid =~ /^--student-id=(.+)$/) { $sid = $1 }
    for (@ARGV) { $sid = $1 if /^--student-id=(.+)$/ }
    die "Usage: remove-student --student-id=ID\n" unless $sid;

    my $students = read_students();
    die "Student '$sid' not found\n" unless delete $students->{$sid};
    write_students($students);

    generate_nginx_config();
    nginx_sys('reload');
    print "Removed student: $sid\n";
}

sub set_student_limits {
    my $sid = shift @ARGV;
    my %opts;
    for (@ARGV) {
        if (/^--student-id=(.+)$/)     { $sid = $1 }
        elsif (/^--max-concurrent=(.+)$/){ $opts{max_concurrent} = $1 }
        elsif (/^--rpm-limit=(.+)$/){ $opts{rpm_limit} = $1 }
        elsif (/^--allow-ip=(.+)$/)    { $opts{allow_ip} = $1 }
        elsif (/^--clear-student-limits$/) { $opts{clear_student_limits} = 1 }
    }
    die "Usage: set-student-limits --student-id=ID [--max-concurrent=N] [--rpm-limit=N]\n" unless $sid;

    my $students = read_students();
    die "Student '$sid' not found\n" unless exists $students->{$sid};

    my $s = $students->{$sid};
    if ($opts{clear_student_limits}) {
        delete $s->{max_concurrent};
        delete $s->{rpm_limit};
    }
    $s->{max_concurrent} = $opts{max_concurrent} if $opts{max_concurrent};
    $s->{rpm_limit} = $opts{rpm_limit} if $opts{rpm_limit};
    $s->{allow_ip} = $opts{allow_ip} if $opts{allow_ip};
    $s->{updated_at} = strftime('%Y-%m-%d %H:%M:%S', localtime);
    write_students($students);

    generate_nginx_config();
    nginx_sys('reload');
    print "Updated limits for: $sid\n";
}

sub list_students {
    my $students = read_students();
    unless (keys %$students) {
        print "(no students)\n";
        return;
    }
    for my $sid (sort keys %$students) {
        my $s = $students->{$sid};
        printf "  %-20s token=%s  ip=%s  rpm=%s  concurrent=%s\n",
            $sid,
            $s->{token} // '-',
            $s->{allow_ip} || '(any)',
            $s->{rpm_limit} || 'default',
            $s->{max_concurrent} || 'default';
    }
}

sub usage {
    print <<"USAGE";
Usage: deploy_nginx_gateway_v022_qwen35b.pl ACTION [options]

Actions:
   setup                    Install nginx + generate config
  start|stop|restart|reload
  generate                 Regenerate nginx config (no restart)
  status                   Show nginx, backend, gateway status
  add-student              --student-id=ID [--token=TOKEN] [--allow-ip=IP]
  remove-student           --student-id=ID
  set-student-limits       --student-id=ID [--rpm-limit=N] [--max-concurrent=N]
  list-students
USAGE
}

main();
